finish scripts

diff --git a/artefact/install b/artefact/install
--- a/artefact/install
+++ b/artefact/install
@@ -59,7 +59,7 @@ then
       echo "You can now run the container image using:"
       echo "./run -r [OPTIONS]"
       echo "See README for more info on running the container" 
-      echo "Run ./install -u to remove the container when finished." 
+      echo "Run ./install -u to remove the image when finished." 
     else   
       echo "Couldn't load the container image into Docker!"
     fi
@@ -68,20 +68,15 @@ then
   fi
 elif [ "$UNINSTALL" == "TRUE" ];
 then 
-  echo "Uninstalling..."
-  CONTAINEDID=$(cat .cid)
-  if [ $? -eq 0 ]
-  then
-    echo "Removing Docker container $CONTAINERID..."
-    docker rm $CONTAINERID > /dev/null
-    if [ $? -eq 0 ]
-    then
-      echo "Container $CONTAINERID removed. All done!" 
-    else
-      echo "Couldn't remove the container $CONTAINERID"
-    fi
+  IMAGE=$(cat .imageID)
+  echo "Removing image  $IMAGE..."
+  docker image rm -f $IMAGE
+  rm -f .imageID
+  if [ $? -eq 0 ] 
+  then 
+    echo "Image removed succesfully. All done!"
   else 
-    echo "No container id found. Has the container been run?" 
-  fi
+    echo "Couldn't remove image."
+  fi 
 fi 
-exit 1
+exit 0
diff --git a/artefact/run b/artefact/run
--- a/artefact/run
+++ b/artefact/run
@@ -1,3 +1,5 @@
+#!/bin/bash
+
 DEMO=FALSE
 CATEGORIES=""
 CATEGORIESFLAG=""
@@ -128,16 +130,18 @@ if [ $? -eq 0 ]
 then 
     CONTAINERID=$(cat .cid)
     echo "Copying results PDF from the container..."
-    docker cp $CONTAINERID:results.pdf .
+    docker cp $CONTAINERID:results.pdf ./$PDFFILE
     if [ $? -eq 0 ]
+    then
         echo "PDF copied to $PDFFILE"
     else 
         echo "Couldn't copy the PDF file!"
     exit 1
     fi
     echo "Copying logfile from the container..."
-    docker cp $CONTAINERID:results.pdf .
+    docker cp $CONTAINERID:benchmarks.log ./$LOGFILE
     if [ $? -eq 0 ]
+    then
         echo "Log file copied to $LOGFILE"
     else 
         echo "Couldn't copy the log file!"
@@ -145,6 +149,14 @@ then
     fi
 else 
     echo "Container failed to run."
-    exit 1
+fi
+echo "Removing container..."
+docker rm $CONTAINERID > /dev/null
+if [ $? -eq 0 ]
+then
+  rm -f .cid
+  echo "Container $CONTAINERID removed. All done!" 
+else
+  echo "Couldn't remove the container $CONTAINERID"
 fi
 exit 0
